-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_grpet_campaign`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_grpet_campaign
-- *
-- * Each is campaign, used to group signatures from various local campaigns into a total
-- *
-- *******************************************************/
CREATE TABLE `civicrm_grpet_campaign` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique GrassrootsPetitionCampaign ID',
     `name` varchar(255)    COMMENT 'Administrative name',
     `label` varchar(255)    COMMENT 'Public name',
     `description` longtext    COMMENT 'Describes the campaign',
     `is_active` tinyint   DEFAULT 1 COMMENT 'Whether to allow these petitions',
     `slug` varchar(255)    COMMENT 'URL path component shared by this campaign\'s petitions',
     `template_what` longtext    COMMENT 'HTML template for the \'What\' of new petitions',
     `template_why` longtext    COMMENT 'HTML template for the \'Why\' of new petitions',
     `template_title` varchar(255)    COMMENT 'HTML template for the title of new petitions',
     `template_image_alt` varchar(255)    COMMENT 'Alternative text for default campaign image',
     `template_tweet` varchar(512)    COMMENT 'Default tweet for new petitions',
     `notify_contact_id` int unsigned    COMMENT 'FK to Contact to notify about new petitions',
     `notify_email` varchar(255)    COMMENT 'Email address to notify about new petitions',
     `thanks_msg_template_id` int unsigned    COMMENT 'FK to MessageTemplate for opted-in signers of this campaign',
     `confirm_msg_template_id` int unsigned    COMMENT 'FK to MessageTemplate for not-opted-in signers of this campaign',
     `download_permissions` varchar(128)    COMMENT 'What data can be downloaded by petition owners by default JSON array or empty to mean global defaults.',
     `allow_mailings` varchar(8)   DEFAULT 'default' COMMENT 'Whether to allow mailings by default. Valid values are default/yes/no' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_grpet_campaign_notify_contact_id FOREIGN KEY (`notify_contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,          CONSTRAINT FK_civicrm_grpet_campaign_thanks_msg_template_id FOREIGN KEY (`thanks_msg_template_id`) REFERENCES `civicrm_msg_template`(`id`) ON DELETE SET NULL,          CONSTRAINT FK_civicrm_grpet_campaign_confirm_msg_template_id FOREIGN KEY (`confirm_msg_template_id`) REFERENCES `civicrm_msg_template`(`id`) ON DELETE SET NULL  
)  ENGINE=InnoDB  ;

 