CREATE TABLE IF NOT EXISTS civicrm_grpet_auth (
  id CHAR(16) NOT NULL PRIMARY KEY,
  validTo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  contact_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  KEY k_validTo (validTo)
);
